version: '3.1'

services:
  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: khoa
    ports:
      - 5555:5432

  adminer:
    image: adminer
    restart: always
    ports:
      - 8000:8080
